# Generated by Django 5.2.12 on 2026-04-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0005_transferencia_efetivada'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='transferencias/comprovantes/', verbose_name='Comprovante de Autorização'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='link_sipac',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link do Processo SIPAC'),
        ),
    ]
