# Generated by Django 5.2.12 on 2026-04-19 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_item_rubrica_alter_perfilusuario_perfil_tipo'),
        ('orcamento', '0009_normalizar_rubricas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPrecoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_importacao', models.CharField(max_length=100, unique=True, verbose_name='Chave de Importação')),
                ('numero_item', models.CharField(max_length=50, verbose_name='Item')),
                ('material', models.TextField(verbose_name='Material')),
                ('rubrica', models.CharField(blank=True, max_length=120, verbose_name='Rubrica')),
                ('unidade', models.CharField(blank=True, max_length=60, verbose_name='Unidade')),
                ('quantidade_empenhada', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Qtd. Emp.')),
                ('marca', models.CharField(blank=True, max_length=160, verbose_name='Marca')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                ('saldo', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Saldo')),
                ('saldo_unidade', models.CharField(blank=True, max_length=60, verbose_name='Saldo Und.')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('pregao_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_preco_orcamento', to='core.pregaoitem', verbose_name='Item RP')),
            ],
            options={
                'verbose_name': 'Item de Registro de Preço',
                'verbose_name_plural': 'Itens de Registro de Preço',
                'ordering': ['registro__numero_pregao', 'numero_item'],
            },
        ),
        migrations.AddField(
            model_name='despesa',
            name='registro_preco_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='orcamento.registroprecoitem', verbose_name='Registro de Preço Vigente'),
        ),
        migrations.CreateModel(
            name='RegistroPrecoVigente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('rp', 'Módulo RP'), ('sipac', 'SIPAC')], max_length=20, verbose_name='Origem')),
                ('numero_pregao', models.CharField(max_length=80, verbose_name='Pregão')),
                ('processo_sipac', models.CharField(blank=True, max_length=80, verbose_name='Processo SIPAC')),
                ('link_sipac', models.URLField(blank=True, max_length=500, verbose_name='Link SIPAC')),
                ('objeto', models.TextField(blank=True, verbose_name='Objeto')),
                ('data_homologacao', models.DateField(blank=True, null=True, verbose_name='Data de Homologação')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_preco_importados', to=settings.AUTH_USER_MODEL)),
                ('pregao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_preco_orcamento', to='core.pregao', verbose_name='Pregão RP')),
            ],
            options={
                'verbose_name': 'Registro de Preço Vigente',
                'verbose_name_plural': 'Registros de Preço Vigentes',
                'ordering': ['origem', 'numero_pregao'],
            },
        ),
        migrations.AddField(
            model_name='registroprecoitem',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamento.registroprecovigente', verbose_name='Registro de Preço'),
        ),
    ]
