# Generated by Django 5.2.12 on 2026-04-19 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_ajuste_validade_irp_registro_preco'),
        ('orcamento', '0010_registroprecoitem_despesa_registro_preco_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroprecoitem',
            name='pregao_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_preco_orcamento', to='core.pregaoitem', verbose_name='Item IRP'),
        ),
        migrations.AlterField(
            model_name='registroprecovigente',
            name='origem',
            field=models.CharField(choices=[('rp', 'Módulo IRP'), ('sipac', 'SIPAC')], max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='registroprecovigente',
            name='pregao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_preco_orcamento', to='core.pregao', verbose_name='Pregão IRP'),
        ),
    ]
