# Generated by Django 5.2.12 on 2026-04-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0011_ajuste_validade_irp_registro_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='rubrica',
            field=models.CharField(blank=True, choices=[('diarias', '339014 - Diárias'), ('aux_financeiro', '339018 - Auxílio Financeiro ao Estudante'), ('material_consumo', '339030 - Material de Consumo'), ('passagens', '339033 - Passagens e Locomoção'), ('estagiarios', '339036 - Estagiários'), ('servico_pf', '339036 - Serviços Pessoa Física'), ('servico_pj', '339039 - Serviços Pessoa Jurídica'), ('servico_pj_tic', '339040 - Serviços PJ | TIC'), ('material_permanente', '449052 - Material Permanente')], max_length=120, verbose_name='Rubrica'),
        ),
        migrations.AlterField(
            model_name='recursoorcamentario',
            name='rubrica',
            field=models.CharField(blank=True, choices=[('diarias', '339014 - Diárias'), ('aux_financeiro', '339018 - Auxílio Financeiro ao Estudante'), ('material_consumo', '339030 - Material de Consumo'), ('passagens', '339033 - Passagens e Locomoção'), ('estagiarios', '339036 - Estagiários'), ('servico_pf', '339036 - Serviços Pessoa Física'), ('servico_pj', '339039 - Serviços Pessoa Jurídica'), ('servico_pj_tic', '339040 - Serviços PJ | TIC'), ('material_permanente', '449052 - Material Permanente')], max_length=120, verbose_name='Rubrica'),
        ),
    ]
