# Generated by Django 5.2.12 on 2026-04-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0012_rubrica_catalogo_orcamento_irp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroprecoitem',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Saldo UFPB'),
        ),
        migrations.AlterField(
            model_name='registroprecoitem',
            name='saldo_unidade',
            field=models.CharField(blank=True, max_length=60, verbose_name='Saldo Unidade'),
        ),
    ]
