# Generated by Django 5.2.12 on 2026-05-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0015_situacaodespesa_despesa_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='pdi_vinculos',
            field=models.JSONField(blank=True, default=list, verbose_name='Vínculos PDI'),
        ),
    ]
