# Generated by Django 5.2.12 on 2026-06-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0017_reativar_situacoes_canonicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='natureza',
            field=models.CharField(max_length=100, verbose_name='Natureza do Recurso'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='rubrica',
            field=models.CharField(blank=True, max_length=120, verbose_name='Rubrica'),
        ),
        migrations.AlterField(
            model_name='recursoorcamentario',
            name='natureza',
            field=models.CharField(max_length=100, verbose_name='Natureza do Recurso'),
        ),
        migrations.AlterField(
            model_name='recursoorcamentario',
            name='rubrica',
            field=models.CharField(blank=True, max_length=120, verbose_name='Rubrica'),
        ),
    ]
