# Generated by Django 4.2.29 on 2026-03-31 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Instruções')),
                ('prazo', models.DateTimeField(verbose_name='Prazo de Encerramento')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('encerrada', 'Encerrada')], default='aberta', max_length=20, verbose_name='Status')),
                ('criada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irps_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IRP',
                'verbose_name_plural': 'IRPs',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Nº')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('unidade', models.CharField(max_length=50, verbose_name='Unidade')),
                ('preco_estimado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Estimado (R$)')),
                ('irp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.irp')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['numero'],
                'unique_together': {('irp', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código SIPAC')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sigla', models.CharField(blank=True, max_length=30, verbose_name='Sigla')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsetores', to='core.setor', verbose_name='Setor Pai')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('irp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.irp')),
                ('setor_localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_localizacao', to='core.setor', verbose_name='Setor de Localização')),
                ('setor_lotacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_lotacao', to='core.setor', verbose_name='Setor de Lotação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'unique_together': {('irp', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('matricula', models.CharField(blank=True, max_length=20, verbose_name='Matrícula')),
                ('is_gestor', models.BooleanField(default=False, verbose_name='É Gestor/Administrador')),
                ('setor_localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizados', to='core.setor', verbose_name='Setor de Localização')),
                ('setor_lotacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotados', to='core.setor', verbose_name='Setor de Lotação')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='RespostaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_item', to='core.item')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_resposta', to='core.resposta')),
            ],
            options={
                'verbose_name': 'Item da Resposta',
                'verbose_name_plural': 'Itens da Resposta',
                'unique_together': {('resposta', 'item')},
            },
        ),
    ]
