# Generated by Django 4.2.29 on 2026-04-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilusuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto',
            field=models.FileField(blank=True, help_text='Imagem JPG, PNG ou GIF. Máximo 10 MB.', null=True, upload_to='fotos_usuarios/', verbose_name='Foto'),
        ),
    ]
