# Generated by Django 4.2.29 on 2026-04-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_perfilusuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='codigo_catmat',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Código CATMAT'),
        ),
        migrations.AddField(
            model_name='item',
            name='numero_dfd',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='N° DFD'),
        ),
        migrations.AddField(
            model_name='item',
            name='quantidade_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quant. Total'),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(verbose_name='Discriminação de Material'),
        ),
        migrations.AlterField(
            model_name='item',
            name='preco_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Vlr. Máx. Aceitável Unitário (R$)'),
        ),
    ]
