# Generated by Django 4.2.29 on 2026-04-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_item_catmat_dfd_qtd'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do Material'),
        ),
        migrations.AlterField(
            model_name='item',
            name='preco_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Referência (R$)'),
        ),
    ]
