# Generated by Django 4.2.29 on 2026-04-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perfil_tipo_homologacao_aprovacao'),
        ('core', '0007_data_migration_homologacao_aprovacao'),
    ]

    operations = [
    ]
