# Generated by Django 4.2.29 on 2026-04-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_aprovacaoct_id_alter_homologacaosetor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='is_gestor',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='perfil_tipo',
            field=models.CharField(choices=[('admin', 'Administrador do Sistema'), ('gestor_irp', 'Gestor de IRP'), ('aprovador_setor', 'Aprovador de Setor Raiz'), ('respondente', 'Respondente'), ('aprovador_ct', 'Aprovador do CT')], default='respondente', max_length=20, verbose_name='Perfil'),
        ),
    ]
