# Generated by Django 4.2.29 on 2026-04-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_irp_prazos_homologacaosetoritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homologacaosetoritem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
