# Generated by Django 5.2.12 on 2026-04-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pregao_pregaoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rubrica',
            field=models.CharField(blank=True, choices=[('material_consumo', 'Material de Consumo'), ('material_permanente', 'Material Permanente')], max_length=20, verbose_name='Rubrica'),
        ),
    ]
