# Generated by Django 5.2.12 on 2026-04-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_irp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregao',
            name='status',
            field=models.CharField(choices=[('em_preparacao', 'Em preparação'), ('em_licitacao', 'Em licitação'), ('homologado', 'Homologado')], default='em_preparacao', max_length=20, verbose_name='Status do Pregão'),
        ),
    ]
