# Generated by Django 5.2.12 on 2026-04-15 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_localizacao_rename_lotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rubrica',
            field=models.CharField(blank=True, choices=[('diarias', 'Diárias'), ('aux_financeiro', 'Auxílio Financeiro ao Estudante'), ('material_consumo', 'Material de Consumo'), ('passagens', 'Passagens e Locomoção'), ('estagiarios', 'Estagiários'), ('servico_pf', 'Serviços Pessoa Física'), ('servico_pj', 'Serviços Pessoa Jurídica'), ('servico_pj_tic', 'Serviços Pessoa Jurídica | TIC'), ('material_permanente', 'Material Permanente')], max_length=30, verbose_name='Rubrica'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='core.setor', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_setor', to='core.setor', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='tipo',
            field=models.CharField(choices=[('centro', 'Centro'), ('direcao', 'Direção de Centro'), ('administrativo', 'Setor Administrativo'), ('departamento', 'Departamento'), ('coordenacao_g', 'Coordenação de Curso'), ('coordenacao_pg', 'Pós-Graduação'), ('laboratorio', 'Laboratório'), ('secretaria', 'Secretaria de Departamento')], default='laboratorio', max_length=20, verbose_name='Tipo'),
        ),
    ]
