# Generated by Django 5.2.12 on 2026-04-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_item_rubrica_alter_perfilusuario_setor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irp',
            name='prazo_aprovacao_ct',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil_tipo',
            field=models.CharField(choices=[('admin', 'Administrador do Sistema'), ('gestor_irp', 'Gestor de IRP'), ('aprovador_setor', 'Aprovador de Setor Raiz'), ('respondente', 'Respondente')], default='respondente', max_length=20, verbose_name='Perfil'),
        ),
        migrations.DeleteModel(
            name='AprovacaoCT',
        ),
    ]
