# Generated by Django 5.2.12 on 2026-04-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_irp_prazo_aprovacao_ct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregaoitem',
            name='situacao',
            field=models.CharField(choices=[('em_preparacao', 'Em preparação'), ('em_licitacao', 'Em licitação'), ('licitado', 'Licitado'), ('nao_licitado', 'Não Licitado')], default='em_licitacao', max_length=20, verbose_name='Situação na Licitação'),
        ),
    ]
