# Generated by Django 5.2.12 on 2026-04-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_pregaoitem_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='data_homologacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Homologação'),
        ),
    ]
