# Generated by Django 5.2.12 on 2026-04-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_perfil_financeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rubrica',
            field=models.CharField(blank=True, choices=[('diarias', '339014 - Diárias'), ('aux_financeiro', '339018 - Auxílio Financeiro ao Estudante'), ('material_consumo', '339030 - Material de Consumo'), ('passagens', '339033 - Passagens e Locomoção'), ('estagiarios', '339036 - Estagiários'), ('servico_pf', '339036 - Serviços Pessoa Física'), ('servico_pj', '339039 - Serviços Pessoa Jurídica'), ('servico_pj_tic', '339040 - Serviços PJ | TIC'), ('material_permanente', '449052 - Material Permanente')], max_length=30, verbose_name='Rubrica'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil_tipo',
            field=models.CharField(choices=[('admin', 'Administrador do Sistema'), ('gestor_irp', 'Assessor de Planejamento'), ('diretor_centro', 'Diretor de Centro'), ('aprovador_setor', 'Chefia Setorial'), ('respondente', 'Respondente'), ('gestor_financeiro', 'Gestor Financeiro'), ('ordenador_despesa', 'Ordenador de Despesa')], default='respondente', max_length=20, verbose_name='Perfil'),
        ),
    ]
