# Generated by Django 5.2.12 on 2026-04-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_item_rubrica_alter_perfilusuario_perfil_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Publicação'),
        ),
    ]
