# Generated by Django 5.2.12 on 2026-09-25 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rubrica_catalogo_orcamento_irp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='setores_adicionais',
            field=models.ManyToManyField(blank=True, help_text='Outros setores pelos quais o usuário também responde IRPs (definidos pela gestão).', related_name='membros_adicionais', to='core.setor', verbose_name='Setores adicionais'),
        ),
        migrations.AlterUniqueTogether(
            name='resposta',
            unique_together={('irp', 'usuario', 'setor')},
        ),
    ]
